_target_:  pytorch_lightning.Trainer

max_epochs: 1000
accelerator: gpu
deterministic: False
detect_anomaly: False
enable_progress_bar: True
strategy: ddp
precision: 16
accumulate_grad_batches: 
val_check_interval: 1000
log_every_n_steps: 1
num_sanity_val_steps: 2
limit_val_batches: 20
limit_test_batches: 1.0

callbacks: "${oc.dict.values: callback}"