version: 1

filters:
  onlyimportant:
    (): src.utils.logging.LevelsFilter
    levels:
    - CRITICAL
    - ERROR
    - WARNING
  noimportant:
    (): src.utils.logging.LevelsFilter
    levels:
    - INFO
    - DEBUG
    - NOTSET

formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    datefmt: '%d/%m/%y %H:%M:%S'

  colorlog:
    (): colorlog.ColoredFormatter
    format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s]
      - %(message)s'
    datefmt: '%d/%m/%y %H:%M:%S'

  log_colors:
    DEBUG: purple
    INFO: green
    WARNING: yellow
    ERROR: red
    CRITICAL: red

handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout

root:
    level: ${logger_level}
    handlers:
    - console

disable_existing_loggers: false